Tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import page_profile.urls as page_profile
import update_status.urls as update_status
import page_stats.urls as page_stats
import add_friend.urls as add_friend

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^update_status/admin/', admin.site.urls),
	url(r'^page_profile/', include(page_profile,namespace='page_profile')),
    url(r'^update_status/', include(update_status,namespace='update_status')),
    url(r'^page_stats/', include(page_stats,namespace='page_stats')),
    url(r'^add_friend/', include(add_friend,namespace='add-friend')),
	url(r'^$', RedirectView.as_view(url='/update_status/',permanent=True),name='index'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend, delete_friend


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
	url(r'^delete/(?P<pk>\d+)/$', delete_friend, name='delete_friend')
 ]

page_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

page_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
	url(r'^delete/(?P<pk>\d+)/$', delete_status, name='delete_status')
]

add_friend/models.py
from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

page_profile/models.py
from django.db import models
from datetime import date

# Create your models here.
class data(models.Model):
	name = "Muhammad Aulia Adil"
	birthdate=date(1998,11,5)
	expertise=["Marketing","Public Speaking","Videography"]
	description="Mahasiswa Sistem Informasi 2016 Fasilkom UI"
	email = "m.aulia.adil@gmail.com"
	gender = "Male"

page_stats/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
    	ordering = ('status', 'created_date')

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan url',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs))
    # message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

page_profile/forms.py
from django import forms

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    status_attrs = {
        'type': 'text',
        'cols': 150,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'Apa yang sedang kamu pikirkan?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

author = 'MT , Adil , Elvan'
response = {}

def index(request):
    response['author'] = author
    friend = Friend.objects.all().order_by('-created_date')
    response['friend'] = friend
    html = 'add_friend/add_friend.html'
    response['friend_form'] = Friend_Form
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['url'] = request.POST['url'] if request.POST['url'] != "" else "Anonymous"
        friendlist = Friend(name=response['name'], url=response['url'])
        friendlist.save()
        return HttpResponseRedirect('/add_friend/')
    else:
        return HttpResponseRedirect('/add_friend/')

def delete_friend(request, pk):
    friend = Friend.objects.filter(pk=pk).first()
    if friend != None:
        friend.delete()
        pass
    return HttpResponseRedirect('/add_friend/')

page_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import data as Data

# Create your views here.
profile=[{'subject' : 'Birthday','value':Data.birthdate.strftime('%d %B %Y')},\
{'subject' : 'Gender','value':Data.gender},\
{'subject' : 'Expertise','value':Data.expertise},\
{'subject' : 'Description','value':Data.description},\
{'subject' : 'Email','value':Data.email}]
name=Data.name
response={}

def index(request):
	response={'author':'MT , Adil , Elvan','profile':profile,'Name':name}
	response ['birthdate']=Data.birthdate.strftime('%d %B %Y')
	response ['gender']=Data.gender
	response ['expertise']=Data.expertise
	response ['description']=Data.description
	response ['email']=Data.email

#	response ['name']='Muhammad Aulia Adil'
#	response ['birthdate']='5 November'
#	response ['gender']='Male'
#	response ['expertise']=['Marketing','Public Speaking','Videography']
#	response ['description']='Mahasiswa Sistem Informasi 2016 Fasilkom UI'
#	response ['email']='m.aulia.adil@gmail.com'
	html = 'page_profile/page_profile.html'
	return render(request, html, response)
	

page_stats/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from update_status.models import Status
from add_friend.models import Friend

# Create your views here.
response = {}
def index(request):
	response['author'] = "MT, Adil, Elvan"
	response ['name']='Muhammad Aulia Adil'
	response ['Friends']=len(Friend.objects.all().order_by('-created_date'))
	response['feed']=len(Status.objects.all().order_by('-created_date'))
	if (len(Status.objects.all().order_by('-created_date'))!=0):
		response ['database']=Status.objects.all().order_by('-created_date')[0]
	else:
		pass
	html = 'Stats/Page_stats.html'
	return render(request, html, response)
	

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

name='Muhammad Aulia Adil'
author='MT, Adil, Elvan'


# Create your views here.
response = {}

def index(request):
    response['author'] = author #TODO Implement yourname
    status = Status.objects.all().order_by('-created_date')
    response['database'] = status
    html = 'update_status/update_status.html'
    response['status_form'] = Status_Form
    response['profile_name'] = name
    return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'])
		status.save()
		return HttpResponseRedirect('/update_status/')
	else:
		return HttpResponseRedirect('/update_status/')

def delete_status(request, pk):
    status = Status.objects.filter(pk=pk).first()
    if status != None:
        status.delete()
        pass
    return HttpResponseRedirect('/update_status/')

add_friend/templates/add_friend/add_friend.html
{% extends "add_friend/layout/base.html" %}

{% block content %}
<div class="container container-fluid">
    <section name="form">
        <h2 class="title">Add Friend</h2>
        <form id="form" method="POST" action="{% url 'add-friend:add_friend' %}" style="color: white; text-shadow: 3px 3px 5px black;">
            {% csrf_token %}
            {{ friend_form }}
            <br>
            <button type="submit" class="btn btn-default">Add Friend</button>
        </form>
    </section>

    <section name="my-list" id="my-list">
        <h2 class="title">List Friend</h2>
        <div class="flex">
            {% if friend %}
                {% for data in friend %}
                    <div class="flex-item">
                        <div class="friend-list">
                            <div class="friend-profile">
                                <div class="friend-profile-left">
                                    <img src="http://www.iconsfind.com/wp-content/uploads/2016/10/20161014_58006bfb44c8d-210x210.png" width="50px" height="50px" alt="my-photo">
                                </div>
                                <div class="friend-profile-right">
                                    {{data.name}}
                                </div>
                            </div>
                            <div class="friend-message">
                                <a href="{{data.url}}">{{data.url}}</a>
                            
                            </div>
                            <div class="friend-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="friend-delete btn-danger">
                                <div class="friend-delete-button" data-id="{{data.id}}">Unfriend</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Kamu belum memiliki teman.</strong>
            </div>
            {% endif %}
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
        $(function() {
            $('.friend-delete-button').click(function() {
                var id = $(this).data('id')
                location.href = "/add_friend/delete/" + id + "/"
            });
        });
    </script>
</div>

{% endblock %}

add_friend/templates/add_friend/layout/base.html
!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">   
    <link rel="stylesheet" href="{% static 'css/add_friend.css' %}" type="text/css">
    <title> 
        {% block title %} Your Friends {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "page_profile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "page_profile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

page_profile/templates/page_profile/edit_profile.html
{% extends "page_profile/layout/base.html" %}
{% load staticfiles%}
    {% block content %}

	<div class="container-fluid" align="center">
		<h1>Profile</h1>
		<section name="profile" style="align-center">
			<img src="https://c1.staticflickr.com/5/4481/37272585896_fb26d30fe6_b.jpg" class="img-circle" widht="200" height="200"></img>
			<h2 class="page_profile_name">{{Name}}</h2>    
		</section>
	</div>
	
	<!--<div class="container-fluid" align="center">
		<table class="borderless">
			{% for data in profile %}
				<tr>
					<td class="page_profile-subject">{{profile.subject}}</td>
					{% if data.subject == 'expertise' %}
					<td class="page_profile-value">
						{% for exp in data.value %}
						<span class="badge">{{exp}}</span>
						{% endfor %}
					</td>
					{% else %}
					<td class="page_profile-value">{{profile.value}}</td>
					{% endif %}
				</tr>
			{% endfor %}
		</table>
	</div>-->
	
	
	<div class="container-fluid" align="center">		
	   <table class="borderless">
			<tbody>
				<tr>
					<td>Birthday</td>
					<td>{{birthdate}}</td>
				</tr>
				<tr>
					<td>Gender</td>
					<td>{{gender}}</td>
				</tr>
				<tr>
					<td>Expertise</td>
					<td>{% for i in expertise %}
						<span class="badge">{{i}}</span>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td>{{description}}</td>
				</tr>
				<tr>
					<td>Email</td>
					<td>{{email}}</td>
				</tr>
			</tbody>
		</table>
	</div>
	{% endblock %}

page_profile/templates/page_profile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="LAB 4">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/ppw.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">   
    <title> 
        {% block title %} My Profile {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "page_profile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "page_profile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

page_profile/templates/page_profile/page_profile.html
{% extends "page_profile/layout/base.html" %}
{% load staticfiles%}
    {% block content %}

	<div class="container-fluid" align="center">
		<h1 class="title">Profile</h1>
		<section name="profile" style="align-center">
			<img src="https://c1.staticflickr.com/5/4481/37272585896_fb26d30fe6_b.jpg" class="img-circle" widht="200" height="200"></img>
			<h2 class="page_profile_name">{{Name}}</h2>    
		</section>
	</div>
	
	<!--<div class="container-fluid" align="center">
		<table class="borderless">
			{% for data in profile %}
				<tr>
					<td class="page_profile-subject">{{profile.subject}}</td>
					{% if data.subject == 'expertise' %}
					<td class="page_profile-value">
						{% for exp in data.value %}
						<span class="badge">{{exp}}</span>
						{% endfor %}
					</td>
					{% else %}
					<td class="page_profile-value">{{profile.value}}</td>
					{% endif %}
				</tr>
			{% endfor %}
		</table>
	</div>-->
	<div class="container-fluid" align="center">		
	   <table class="borderless">
			<tbody>
				<tr>
					<td>Birthday</td>
					<td>{{birthdate}}</td>
				</tr>
				<tr>
					<td>Gender</td>
					<td>{{gender}}</td>
				</tr>
				<tr>
					<td>Expertise</td>
					<td>{% for i in expertise %}
						<span class="badge">{{i}}</span>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td>{{description}}</td>
				</tr>
				<tr>
					<td>Email</td>
					<td>{{email}}</td>
				</tr>
			</tbody>
		</table>
	</div>
	{% endblock %}

page_profile/templates/page_profile/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p class="footer">Made with Love by {{author}}</p>

page_profile/templates/page_profile/partials/header.html
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'page_profile:index' %}"><img src="http://findicons.com/files/icons/1580/devine_icons_part_2/128/home.png" width="30px" height="30px"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right navbar-header">
            <!-- LINK MENUJU table, dan link menuju home#form -->
            <li><a href="{% url 'update_status:add_status' %}"> Status </a></li>
            <li><a href="{% url 'page_profile:index' %}"> Profile </a> </li>
            <li><a href="{% url 'add-friend:index' %}"> Friends </a> </li>
            <li><a href="{% url 'page_stats:index' %}"> Stats </a> </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

page_stats/templates/Stats/Page_stats.html
{% extends "Stats/layout/base.html" %}
{% block content %}
<div class="container">
    <section name="input-list" id="input-list">
        <h1 class="title" style=>Statistics</h1>
    </section>
    <section name="profile" style="align-left">
        <div class="nempel">
            <img src="https://c1.staticflickr.com/5/4481/37272585896_fb26d30fe6_b.jpg" class="img-circle" widht="200" height="200"></img>
            <span class="biar_beda">
            {{name}}
         </span>
        </div>   
        </section>
        <div class="container-fluid" align="center"><div class="row">
        <div class="col-md-6" style="font-size: 30px;color:white">Friends: {{Friends}}</div>
        <div class="col-md-6" style="font-size: 30px;color:white">feeds:{{feed}}</div>
    </div>
        <div class="col-md-6" style="font-size: 30px;color:white">Latest Post:
            <div class="biar_keren">
                {% if database %}
                    <div class="flex-item">
                        <div class="status-list">
                            <div class="status-profile">
                                <div class="status-profile-left">
                                    <img src="https://c1.staticflickr.com/5/4481/37272585896_fb26d30fe6_b.jpg" class="img-circle" width="50px" height="50px" alt="my-photo"></a>
                                    <span class="status-profile-right">
                                    {{name}}
                                </span>
                                </div>
                            </div>
                            <div class="status-message">
                                {{database.status}}
                            </div>
                            <div class="status-date">
                                {{database.created_date}}
                            </div>
                        </div>
                    </div>
            {% else %}
            <strong>Anda Belum Pernah Buat Status.</strong>
            {% endif %}
        </div>
    </div>
</div>
                            
{% endblock %}  

page_stats/templates/Stats/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="LAB 4">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">   
    <link rel="stylesheet" href="{% static 'css/page_stats.css' %}" type="text/css">
    <title> 
        {% block title %} Your Stats {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "page_profile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "page_profile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

update_status/templates/update_status/layout/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Update Status">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />

    <!-- bootstrap csss -->

    <title>
        {% block title %} Update Your Status {% endblock %}
    </title>
</head>

<body>
    <header>
            {% include "page_profile/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "page_profile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

update_status/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}

{% block content %}
<div class="container container-fluid">
    <section name="input-list" id="input-list">
        <h1 class="title">Kenalan Yuk</h1>
        <form id="form" method="POST" action="{% url 'update_status:add_status' %}">
            <h2>Update Status</h2>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block" value="Post">
            <br>
        </form>
    </section>
    
    <section name="my-list" id="my-list">
        <h2 class="title">Your Status</h2>
        <div class="flex">
            {% if database %}
                {% for data in database %}
                    <div class="flex-item">
                        <div class="status-list">
                            <div class="status-profile">
                                <div class="status-profile-left">
                                    <a href="{% url 'page_profile:index' %}">
                                    <img src="https://c1.staticflickr.com/5/4481/37272585896_fb26d30fe6_b.jpg" width="50px" height="50px" alt="my-photo"></a>
                                </div>
                                <div class="status-profile-right">
                                    {{profile_name}}
                                </div>
                            </div>
                            <div class="status-message">
                                {{data.status}}
                            </div>
                            <div class="status-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="status-delete">
                                <div class="status-delete-button" data-id="{{data.id}}">Delete</div>
                            </div>
                        </div>       
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Kamu belum membuat Status. </strong>
            </div>
            {% endif %}
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
        $(function() {
            $('.status-delete-button').click(function() {
                var id = $(this).data('id')
                location.href = "/update_status/delete/" + id + "/"
            });
        });
    </script>
</div>

{% endblock %}  